In [14]:
from tensorflow.keras.preprocessing.text import one_hot

In [15]:
### sentences
sent = [
    "The glass of milk",
    "The glass of juice",
    "the glass of milk",
    "the cup of tea",
    "I am a good boy",
    "understand the meaning of words"
]

In [16]:
## Define the vocabulary size
vocab_size = 10000

In [17]:
### One Hot Representation 
one_hot_representations = [one_hot(words, vocab_size) for words in sent]
one_hot_representations

[[8907, 4927, 3468, 5475],
 [8907, 4927, 3468, 8176],
 [8907, 4927, 3468, 5475],
 [8907, 2256, 3468, 6241],
 [466, 159, 6704, 4912, 2451],
 [9816, 8907, 6845, 3468, 4809]]

In [18]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_representations,padding='pre',maxlen=sent_length)
print(embedded_docs) # pre means 0's at first

[[   0    0    0    0 8907 4927 3468 5475]
 [   0    0    0    0 8907 4927 3468 8176]
 [   0    0    0    0 8907 4927 3468 5475]
 [   0    0    0    0 8907 2256 3468 6241]
 [   0    0    0  466  159 6704 4912 2451]
 [   0    0    0 9816 8907 6845 3468 4809]]


In [19]:
## feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\DL Project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 434ms/step


array([[[ 0.0166543 ,  0.02760741, -0.02694432, -0.01416862,
          0.04127483,  0.02376059, -0.03526009, -0.0289946 ,
          0.00445797, -0.01584857],
        [ 0.0166543 ,  0.02760741, -0.02694432, -0.01416862,
          0.04127483,  0.02376059, -0.03526009, -0.0289946 ,
          0.00445797, -0.01584857],
        [ 0.0166543 ,  0.02760741, -0.02694432, -0.01416862,
          0.04127483,  0.02376059, -0.03526009, -0.0289946 ,
          0.00445797, -0.01584857],
        [ 0.0166543 ,  0.02760741, -0.02694432, -0.01416862,
          0.04127483,  0.02376059, -0.03526009, -0.0289946 ,
          0.00445797, -0.01584857],
        [ 0.01830867, -0.00635712,  0.01338651,  0.02722473,
         -0.02086726,  0.02694103, -0.04804608,  0.00085957,
          0.01345134,  0.0480826 ],
        [-0.00788457, -0.00090367, -0.04327408,  0.00033708,
          0.0408798 ,  0.02050021,  0.02044841,  0.00358446,
         -0.015034  , -0.00492745],
        [ 0.01881334,  0.04656941, -0.01497314, -0.0

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 8907, 4927, 3468, 5475], dtype=int32)

In [24]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>